name: Docker deploy

inputs:
  REGISTRY_URL:
    required: true
    type: string
  PROJECT_NAME:
    required: true
    type: string
  DOCKER_COMPOSE_PATH:
    required: true
    type: string
  DOCKER_COMPOSE_EXTRA_ARGS:
    required: false
    type: string
    default: ''
  GITHUB_TOKEN:
    required: true
    type: string

runs:
    using: composite

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ inputs.GITHUB_TOKEN }}
      - name: Pull docker images
        shell: 'sh'
        run: docker-compose --project-name ${{ inputs.PROJECT_NAME }} -f ${{ inputs.DOCKER_COMPOSE_PATH }} ${{ inputs.DOCKER_COMPOSE_EXTRA_ARGS }} pull
      - name: Run docker-compose up
        shell: 'sh'
        run: docker-compose --project-name ${{ inputs.PROJECT_NAME }} -f ${{ inputs.DOCKER_COMPOSE_PATH }} ${{ inputs.DOCKER_COMPOSE_EXTRA_ARGS }} up --build --remove-orphans --force-recreate -d


