name: "Set Maven Settings"
description: "Sets Maven settings using s4u/maven-settings-action"
inputs:
  MAVEN_USER_HOME:
    description: "Maven user home directory"
    required: true
  MAVEN_SERVER_ID:
    description: "Maven server ID"
    required: false
  MAVEN_SERVER_USERNAME:
    description: "Maven server username"
    required: false
  MAVEN_SERVER_PASSWORD:
    description: "Maven server password"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set maven settings
      uses: s4u/maven-settings-action@v3.1.0
      if: ${{ inputs.MAVEN_SERVER_ID != '' }}
      with:
        path: "${{ inputs.MAVEN_USER_HOME }}/settings.xml"
        servers: |
          [{ "id": "${{ inputs.MAVEN_SERVER_ID }}",
              "username": "${{ inputs.MAVEN_SERVER_USERNAME }}",
              "password": "${{ inputs.MAVEN_SERVER_PASSWORD }}"
          }]

    - name: Set default maven settings
      uses : s4u/maven-settings-action@v3.1.0
      if: ${{ inputs.MAVEN_SERVER_ID == '' }}
      with:
        path: "${{ inputs.MAVEN_USER_HOME }}/settings.xml"

