#IMPORTANT: THIS ACTION MUST BE EXECUTED ON A CLEAN ENVIRONMENT WITH AZ INSTALLED

name: Deploy app to Azure Storage

inputs:
  WORKING_DIRECTORY:
    required: true
    type: string
  BINARIES_DIRECTORY:
    required: true
    type: string
  AZURE_CREDENTIALS:
    required: true
    type: string
  STORAGE_ACCOUNT_NAME:
    required: true
    type: string
  CDN_PROFILE_NAME:
    required: false
    type: string
    default: ""
  CDN_ENDPOINT_NAME:
    required: false
    type: string
    default: ""
  CDN_RG_NAME:
    required: false
    type: string
    default: ""
  FD_RG_NAME:
    required: false
    type: string
    default: ""
  FD_ENDPOINT_NAME:
    required: false
    type: string
    default: ""
  FD_DOMAIN_NAME:
    required: false
    type: string
    default: ""
  FD_PROFILE_NAME:
    required: false
    type: string
    default: ""
  PURGE_CONTENT_PATHS:
    required: false
    type: string
    default: "/*"

runs:
  using: composite
  steps:
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.AZURE_CREDENTIALS }}

    - name: Sync to Azure Storage ($web)
      shell: bash
      run: |
        SRC="${{ inputs.WORKING_DIRECTORY }}/${{ inputs.BINARIES_DIRECTORY }}"
        echo "Deleting existing blobs from '$web' container..."
        az storage blob delete-batch \
          --account-name "${{ inputs.STORAGE_ACCOUNT_NAME }}" \
          --source '$web' \
          --only-show-errors
        echo "Uploading '$SRC' -> '$web'..."
        az storage blob upload-batch \
          --account-name "${{ inputs.STORAGE_ACCOUNT_NAME }}" \
          --destination '$web' \
          --source "$SRC" \
          --only-show-errors

    - name: Purge CDN endpoint
      shell: "bash"
      if: ${{ inputs.CDN_RG_NAME != '' }}
      run: |
        az cdn endpoint purge --content-paths  "${{ inputs.PURGE_CONTENT_PATHS }}" --profile-name "${{ inputs.CDN_PROFILE_NAME }}" --name "${{ inputs.CDN_ENDPOINT_NAME }}" --resource-group "${{ inputs.CDN_RG_NAME }}" --no-wait

    - name: Purge Azure Front Door endpoint
      shell: "bash"
      if: ${{ inputs.FD_RG_NAME != '' }}
      run: |
        DOMAIN_PARAM=""
        if [ -n "${{ inputs.FD_DOMAIN_NAME }}" ]; then
          DOMAIN_PARAM="--domains ${{ inputs.FD_DOMAIN_NAME }}"
        fi
        az afd endpoint purge --content-paths  "${{ inputs.PURGE_CONTENT_PATHS }}" --endpoint-name "${{ inputs.FD_ENDPOINT_NAME }}" --resource-group "${{ inputs.FD_RG_NAME }}" $DOMAIN_PARAM --profile-name "${{ inputs.FD_PROFILE_NAME }}" --no-wait

    - name: Azure logout
      shell: "bash"
      if: always()
      continue-on-error: true
      run: |
        az logout
        az cache purge
        az account clear
