name: .NET install, build and publish

inputs:
  WORKING_DIRECTORY:
    required: true
    type: string
  BUILD_CONFIG:
    required: true
    type: string
  PROJECT:
    requires: true
    type: string
  OUTPUT_DIRECTORY:
    required: true
    type: string
  SHELL:
    required: false
    type: string
    default: "bash"
  DISABLE_CACHE:
    required: false
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: Build
      uses: zupit-it/pipeline-templates/.github/actions/dotnet/build@ZCH-126/caching-by-suffix
      with:
        WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
        BUILD_CONFIG: ${{ inputs.BUILD_CONFIG }}
        SHELL: ${{ inputs.SHELL }}
        DISABLE_CACHE: ${{ inputs.DISABLE_CACHE }}

    - name: Publish
      uses: zupit-it/pipeline-templates/.github/actions/dotnet/publish@v1.27.3
      with:
        WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
        PROJECT: ${{ inputs.PROJECT }}
        OUTPUT_DIRECTORY: ${{ inputs.OUTPUT_DIRECTORY }}
        BUILD_CONFIG: ${{ inputs.BUILD_CONFIG }}
        SHELL: ${{ inputs.SHELL }}
