name: .NET format

inputs:
  WORKING_DIRECTORY:
    required: true
    type: string
  SHELL:
    required: false
    type: string
    default: 'bash'
  CSHARPIER_VERSION:
    required: false
    type: string
    default: ''

runs:
  using: composite
  steps:
    - name: Install code formatter
      shell: ${{ inputs.SHELL }}
      run: dotnet tool update --tool-path /tmp/dotnet-tools csharpier ${{ inputs.CSHARPIER_VERSION != '' && '--version' || '' }} ${{ inputs.CSHARPIER_VERSION }}
      working-directory: ${{ inputs.WORKING_DIRECTORY }}

    - name: Check code formatting
      shell: ${{ inputs.SHELL }}
      run: /tmp/dotnet-tools/dotnet-csharpier . --check
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
