name: Delete tagged images

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: "zupit-agents"
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: "Container"
      DIND_IMAGE:
        required: false
        type: string
        default: "docker:26.0.0-dind"
      IMAGE_NAME:
        required: true
        type: string
      KEEP_AT_LEAST:
        required: false
        type: number
        default: 2
      DRY_RUN:
        required: false
        type: boolean
        default: false

jobs:
  to-lowercase-repository-name:
    name: "Get repository name to lowercase"
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container:
      image: ${{ inputs.DIND_IMAGE }}

    outputs:
      REPOSITORY_NAME: ${{ steps.string.outputs.lowercase }}

    steps:
      - id: string
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ github.event.repository.name }}

  clean-untagged-images:
    name: "Delete untagged images ${{ needs.to-lowercase-repository-name.outputs.REPOSITORY_NAME }}/${{ inputs.IMAGE_NAME }}"
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container:
      image: ${{ inputs.DIND_IMAGE }}
    needs: [to-lowercase-repository-name]
    steps:
      - name: "Delete untagged images ${{ needs.to-lowercase-repository-name.outputs.REPOSITORY_NAME }}*"
        uses: snok/container-retention-policy@v1.5.1
        with:
          image-names: "${{ needs.to-lowercase-repository-name.outputs.REPOSITORY_NAME }}/*"
          cut-off: now UTC
          timestamp-to-use: created_at
          account-type: org
          org-name: zupit-it
          untagged-only: true
          keep-at-least: 0
          token: ${{ secrets.RETENTION_POLICY_TOKEN }}

  clean-staging-tagged-images:
    name: "Delete staging tagged images ${{ github.event.repository.name }}/${{ inputs.IMAGE_NAME }}"
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container:
      image: ${{ inputs.DIND_IMAGE }}
    needs: [clean-untagged-images]
    steps:
      - name: Delete tagged images ${{ inputs.IMAGE_NAME }}
        uses: vlaurin/action-ghcr-prune@v0.4.0
        with:
          container: "${{ github.event.repository.name }}/${{ inputs.IMAGE_NAME }}"
          organization: zupit-it
          keep-last: ${{ inputs.KEEP_AT_LEAST }}
          tag-regex: v[0-9]+.[0-9]+.[0-9]+-rc
          untagged: false
          token: ${{ secrets.RETENTION_POLICY_TOKEN }}
          dry-run: ${{ inputs.DRY_RUN }}

  clean-production-tagged-images:
    name: "Delete production tagged images ${{ github.event.repository.name }}/${{ inputs.IMAGE_NAME }}"
    needs: [clean-untagged-images]
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container:
      image: ${{ inputs.DIND_IMAGE }}
    steps:
      - name: Delete tagged images ${{ inputs.IMAGE_NAME }}
        uses: vlaurin/action-ghcr-prune@v0.4.0
        with:
          container: "${{ github.event.repository.name }}/${{ inputs.IMAGE_NAME }}"
          organization: zupit-it
          keep-last: ${{ inputs.KEEP_AT_LEAST }}
          tag-regex: v[0-9]+.[0-9]+.[0-9]+
          keep-tags-regexes: v[0-9]+.[0-9]+.[0-9]+-rc
          untagged: false
          token: ${{ secrets.RETENTION_POLICY_TOKEN }}
          dry-run: ${{ inputs.DRY_RUN }}
