name: .NET build and deploy to Azure WebApp

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: "ubuntu-24.04"
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: "Container"
      RELEASE_ENVIRONMENT:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      PROJECT:
        required: true
        type: string
      WEBAPP_NAME:
        required: true
        type: string
      CHECKOUT_REF:
        required: false
        type: string
        default: ""
      ENV_VARIABLES:
        required: false
        type: string
        default: "{}"
      DOTNET_IMAGE:
        required: false
        type: string
        default: "mcr.microsoft.com/dotnet/sdk:7.0"
      AZURE_CLI_IMAGE:
        required: false
        type: string
        default: "mcr.microsoft.com/azure-cli:2.69.0"
      TDNF_PACKAGE_MANAGER_INSTALL_TAR:
        required: false
        type: boolean
        default: true
      DISABLE_CACHE:
        required: false
        type: boolean
        default: false
      CHECK_WORKDIR_CHANGES:
        required: false
        type: boolean
        default: false
        description: "When true, enables change detection. When false, always runs jobs"
      CHECK_CUSTOM_DIR:
        required: false
        type: string
        default: ""
        description: "Override directory to check for changes. Defaults to WORKING_DIRECTORY if empty"
      CHECK_CHANGES_BY_JOBS:
        required: false
        type: string
        default: "all"
        description: "JSON array of job IDs to run change detection for. The default 'all' runs for all jobs"

env: "${{secrets}}"

jobs:
  workdir-has-changes:
    runs-on: ${{ inputs.RUN_ON }}
    container: buildpack-deps:24.04-scm
    outputs:
      changes-detected: ${{ steps.filter.outputs.changes-detected }}
    steps:
      - name: Set CHECK_DIR to custom directory if provided
        if: ${{ inputs.CHECK_CUSTOM_DIR != '' }}
        run: echo "CHECK_DIR=${{ inputs.CHECK_CUSTOM_DIR }}" >> $GITHUB_ENV
      - name: Set default CHECK_DIR
        if: ${{ inputs.CHECK_CUSTOM_DIR == '' }}
        run: echo "CHECK_DIR=${{ inputs.WORKING_DIRECTORY }}" >> $GITHUB_ENV
      - name: Configure Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changes-detected:
              - "${{ inputs.WORKING_DIRECTORY }}/**"

  build:
    needs: workdir-has-changes
    if: ${{ !inputs.CHECK_WORKDIR_CHANGES || (needs.workdir-has-changes.outputs.changes-detected == 'true' && (inputs.CHECK_CHANGES_BY_JOBS == 'all' || contains(fromJson(inputs.CHECK_CHANGES_BY_JOBS), github.job)))}}
    runs-on: ${{ inputs.RUN_ON }}
    container:
      image: ${{ inputs.DOTNET_IMAGE }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    outputs:
      ARTIFACT_NAME: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}

    env: ${{ fromJson(inputs.ENV_VARIABLES) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.CHECKOUT_REF }}

      - name: Generate artifact name
        id: artifact-name
        uses: zupit-it/pipeline-templates/.github/actions/artifact/generate-name@test/warpbuild-vs-github-runners
        with:
          NAME_PREFIX: dotnet-build

      - name: Build
        uses: zupit-it/pipeline-templates/.github/actions/dotnet/release@test/warpbuild-vs-github-runners
        with:
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          BUILD_CONFIG: "Release"
          PROJECT: ${{ inputs.PROJECT }}
          OUTPUT_DIRECTORY: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}
          DISABLE_CACHE: ${{ inputs.DISABLE_CACHE }}

      - name: Upload build artifact
        uses: zupit-it/pipeline-templates/.github/actions/artifact/upload@test/warpbuild-vs-github-runners
        with:
          SOURCE_FOLDER: ${{ inputs.WORKING_DIRECTORY }}/${{ steps.artifact-name.outputs.ARTIFACT_NAME }}
          ARTIFACT_NAME: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}

  deploy:
    if: ${{ !inputs.CHECK_WORKDIR_CHANGES || (needs.workdir-has-changes.outputs.changes-detected == 'true' && (inputs.CHECK_CHANGES_BY_JOBS == 'all' || contains(fromJson(inputs.CHECK_CHANGES_BY_JOBS), github.job)))}}
    runs-on: ${{ inputs.RUN_ON }}
    env: ${{ fromJson(inputs.ENV_VARIABLES) }}
    environment: ${{ inputs.RELEASE_ENVIRONMENT }}
    container:
      image: ${{ inputs.AZURE_CLI_IMAGE }}
      env:
        GNUPGHOME: /root/.gnupg

    needs: [workdir-has-changes, build]
    steps:
      - name: Installing tar package with tdnf
        if: ${{ inputs.TDNF_PACKAGE_MANAGER_INSTALL_TAR == true }}
        run: |
          tdnf install -y tar

      - name: Download build artifact
        id: output-folder
        uses: zupit-it/pipeline-templates/.github/actions/artifact/download@test/warpbuild-vs-github-runners
        with:
          ARTIFACT_NAME: ${{ needs.build.outputs.ARTIFACT_NAME }}

      - name: Publish to Azure App Service
        uses: zupit-it/pipeline-templates/.github/actions/azure/app-service/deploy@test/warpbuild-vs-github-runners
        with:
          WORKING_DIRECTORY: ${{ steps.output-folder.outputs.OUTPUT_FOLDER }}
          BINARIES_DIRECTORY: ""
          AZURE_CREDENTIALS: ${{ secrets.CI_AZURE_CREDENTIALS }}
          WEBAPP_NAME: ${{ inputs.WEBAPP_NAME }}

  jobs-succeded:
    needs: [build, deploy]
    runs-on: ${{ inputs.RUN_ON }}
    if: ${{ always() }}
    steps:
      - name: "Check if jobs succeeded"
        run: if [[ "${{ needs.build.result }}" == "failure" || "${{ needs.deploy.result }}" == "failure" ]]; then exit 1; fi
