name: Add Jira description to pr

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: "warp-ubuntu-latest-x64-4x"
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: "Container"
      DIND_IMAGE:
        required: false
        type: string
        default: "docker:26.0.0-dind"

jobs:
  jira-description:
    runs-on: ${{ inputs.RUN_ON }}
    container:
      image: ${{ inputs.DIND_IMAGE }}

    steps:
      - uses: cakeinpanic/jira-description-action@v0.4.0
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_USER_EMAIL}}:${{ secrets.JIRA_API_TOKEN }}
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
          use: branch
