name: Lint, check and build a Javascript app

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: "zupit-agents"
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: "Container"
      NODE_VERSION:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      RUN:
        required: false
        type: boolean
        default: true
      PROJECT:
        required: false
        type: string
        default: ""
      IMAGE:
        required: false
        type: string
        default: "ubuntu:23.04"

env: "${{secrets}}"

jobs:
  lint-check-build:
    if: ${{ inputs.RUN }}
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container:
      image: ${{ inputs.IMAGE }}
    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ inputs.NODE_VERSION }}
        uses: buildjet/setup-node@v4.0.4
        with:
          node-version: ${{ inputs.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: ${{ inputs.WORKING_DIRECTORY }}/**/package-lock.json

      # Set NPM cache directory to a new clean directory to avoid sharing with other runners
      - name: Set NPM cache directory
        run: echo "NPM_CONFIG_CACHE=~/.npm$(npm -v)" >> $GITHUB_ENV

      - name: Authenticate with private NPM package
        if: ${{ env.github_token }}
        run: echo "//npm.pkg.github.com/:_authToken=${{ env.github_token }}" > ~/.npmrc

      - run: npm ci

      # GENERIC
      - run: npm run ci:format:check
        if: ${{ inputs.PROJECT == '' }}

      - run: npm run ci:lint
        if: ${{ inputs.PROJECT == '' }}

      - run: npm run ci:build
        if: ${{ inputs.PROJECT == '' }}

      # PROJECT SPECIFIC
      - run: npm run ${{ inputs.PROJECT }}:ci:format:check
        if: ${{ inputs.PROJECT != '' }}

      - run: npm run ${{ inputs.PROJECT }}:ci:lint
        if: ${{ inputs.PROJECT != '' }}

      - run: npm run ${{ inputs.PROJECT }}:ci:build
        if: ${{ inputs.PROJECT != '' }}
