name: Node build and deploy to Azure Storage

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: "ubuntu-24.04"
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: "Container"
      NODE_VERSION:
        required: true
        type: string
      RELEASE_ENVIRONMENT:
        required: true
        type: string
      WORKING_DIRECTORY:
        required: true
        type: string
      STORAGE_ACCOUNT_NAME:
        required: true
        type: string
      DIST_PATH:
        required: true
        type: string
      BUILD_ARGS:
        required: false
        type: string
        default: ""
      CDN_PROFILE_NAME:
        required: false
        type: string
        default: ""
      CDN_ENDPOINT_NAME:
        required: false
        type: string
        default: ""
      CDN_RG_NAME:
        required: false
        type: string
        default: ""
      FD_RG_NAME:
        required: false
        type: string
        default: ""
      FD_ENDPOINT_NAME:
        required: false
        type: string
        default: ""
      FD_DOMAIN_NAME:
        required: false
        type: string
        default: ""
      FD_PROFILE_NAME:
        required: false
        type: string
        default: ""
      NEW_CACHE_STRATEGY:
        required: false
        type: boolean
        default: false
      PURGE_CONTENT_PATHS:
        required: false
        type: string
        default: "/*"
      ENV_VARIABLES:
        required: false
        type: string
        default: "{}"
      PROJECT:
        required: false
        type: string
        default: ""
      IMAGE:
        required: false
        type: string
        default: "ubuntu:23.04"
      AZURE_CLI_IMAGE:
        required: false
        type: string
        default: "mcr.microsoft.com/azure-cli:2.69.0"
      TDNF_PACKAGE_MANAGER_INSTALL_TAR:
        required: false
        type: boolean
        default: true
      CHECKOUT_REF:
        required: false
        type: string
        default: ""
      CHECK_WORKDIR_CHANGES:
        required: false
        type: boolean
        default: false
        description: "When true, enables change detection. When false, always runs jobs"
      CHECK_CUSTOM_DIR:
        required: false
        type: string
        default: ""
        description: "Override directory to check for changes. Defaults to WORKING_DIRECTORY if empty"
      CHECK_CHANGES_BY_JOBS:
        required: false
        type: string
        default: "all"
        description: "JSON array of job IDs to run change detection for. The default 'all' runs for all jobs"

env: "${{secrets}}"

jobs:
  workdir-has-changes:
    runs-on: ${{ inputs.RUN_ON }}
    container: buildpack-deps:24.04-scm
    outputs:
      changes-detected: ${{ steps.filter.outputs.changes-detected }}
    steps:
      - name: Set CHECK_DIR to custom directory if provided
        if: ${{ inputs.CHECK_CUSTOM_DIR != '' }}
        run: echo "CHECK_DIR=${{ inputs.CHECK_CUSTOM_DIR }}" >> $GITHUB_ENV
      - name: Set default CHECK_DIR
        if: ${{ inputs.CHECK_CUSTOM_DIR == '' }}
        run: echo "CHECK_DIR=${{ inputs.WORKING_DIRECTORY }}" >> $GITHUB_ENV
      - name: Configure Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changes-detected:
              - "${{ inputs.WORKING_DIRECTORY }}/**"

  build-node-project:
    needs: workdir-has-changes
    if: ${{ !inputs.CHECK_WORKDIR_CHANGES || (needs.workdir-has-changes.outputs.changes-detected == 'true' && (inputs.CHECK_CHANGES_BY_JOBS == 'all' || contains(fromJson(inputs.CHECK_CHANGES_BY_JOBS), github.job)))}}
    runs-on: ${{ inputs.RUN_ON }}
    container:
      image: ${{ inputs.IMAGE }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    outputs:
      ARTIFACT_NAME: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}

    env: ${{ fromJson(inputs.ENV_VARIABLES) }}
    steps:
      - name: Generate artifact name
        id: artifact-name
        uses: zupit-it/pipeline-templates/.github/actions/artifact/generate-name@test/warpbuild-vs-github-runners
        with:
          NAME_PREFIX: node-build

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.CHECKOUT_REF }}

      - name: Build
        uses: zupit-it/pipeline-templates/.github/actions/node/build@test/warpbuild-vs-github-runners
        with:
          NODE_VERSION: ${{ inputs.NODE_VERSION }}
          RELEASE_ENVIRONMENT: ${{ inputs.RELEASE_ENVIRONMENT }}
          WORKING_DIRECTORY: ${{ inputs.WORKING_DIRECTORY }}
          BUILD_ARGS: ${{ inputs.BUILD_ARGS }}
          PROJECT: ${{ inputs.PROJECT }}
          CHECKOUT_REF: ${{ inputs.CHECKOUT_REF }}

      - name: Upload build artifact
        uses: zupit-it/pipeline-templates/.github/actions/artifact/upload@test/warpbuild-vs-github-runners
        with:
          SOURCE_FOLDER: ${{ inputs.WORKING_DIRECTORY }}/${{ inputs.DIST_PATH }}
          ARTIFACT_NAME: ${{ steps.artifact-name.outputs.ARTIFACT_NAME }}

  node-deploy-azure-storage:
    needs: [workdir-has-changes, build-node-project]
    if: ${{ !inputs.CHECK_WORKDIR_CHANGES || (needs.workdir-has-changes.outputs.changes-detected == 'true' && (inputs.CHECK_CHANGES_BY_JOBS == 'all' || contains(fromJson(inputs.CHECK_CHANGES_BY_JOBS), github.job)))}}
    runs-on: ${{ inputs.RUN_ON }}
    env: ${{ fromJson(inputs.ENV_VARIABLES) }}
    environment: ${{ inputs.RELEASE_ENVIRONMENT }}
    container:
      image: ${{ inputs.AZURE_CLI_IMAGE }}
      env:
        GNUPGHOME: /root/.gnupg

    steps:
      - name: Installing tar package with tdnf
        if: ${{ inputs.TDNF_PACKAGE_MANAGER_INSTALL_TAR == true }}
        run: |
          tdnf install -y tar

      - name: Download build artifact
        id: output-folder
        uses: zupit-it/pipeline-templates/.github/actions/artifact/download@test/warpbuild-vs-github-runners
        with:
          ARTIFACT_NAME: ${{ needs.build-node-project.outputs.ARTIFACT_NAME }}

      - name: Deploy to Azure Storage
        uses: zupit-it/pipeline-templates/.github/actions/azure/storage/deploy@test/warpbuild-vs-github-runners
        with:
          WORKING_DIRECTORY: ${{ steps.output-folder.outputs.OUTPUT_FOLDER }}
          BINARIES_DIRECTORY: ""
          AZURE_CREDENTIALS: ${{ secrets.CI_AZURE_CREDENTIALS }}
          STORAGE_ACCOUNT_NAME: ${{ inputs.STORAGE_ACCOUNT_NAME }}
          CDN_PROFILE_NAME: ${{ inputs.CDN_PROFILE_NAME }}
          CDN_ENDPOINT_NAME: ${{ inputs.CDN_ENDPOINT_NAME }}
          CDN_RG_NAME: ${{ inputs.CDN_RG_NAME }}
          FD_RG_NAME: ${{ inputs.FD_RG_NAME }}
          FD_ENDPOINT_NAME: ${{ inputs.FD_ENDPOINT_NAME }}
          FD_DOMAIN_NAME: ${{ inputs.FD_DOMAIN_NAME }}
          FD_PROFILE_NAME: ${{ inputs.FD_PROFILE_NAME }}
          NEW_CACHE_STRATEGY: ${{ inputs.NEW_CACHE_STRATEGY }}
          PURGE_CONTENT_PATHS: ${{ inputs.PURGE_CONTENT_PATHS }}

  jobs-succeded:
    needs: [build-node-project, node-deploy-azure-storage]
    runs-on: ${{ inputs.RUN_ON }}
    if: ${{ always() }}
    steps:
      - name: "Check if jobs succeeded"
        run: if [[ "${{ needs.build-node-project.result }}" == "failure" || "${{ needs.node-deploy-azure-storage.result }}" == "failure" ]]; then exit 1; fi
