name: Pull request workflow

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  format-check:
    name: Format check
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18.16.0
      - run: npm ci --ignore-scripts
      - run: npm run format:check

  lint-pr:
    name: Lint PR
    runs-on: "ubuntu-24.04"
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
