name: Springboot common

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
      JAVA_IMAGE:
        required: true
        type: string
      COVERAGE_ARTIFACT_NAME:
        required: false
        type: string
        default: "target"
      MAVEN_USER_HOME:
        required: false
        type: string
        default: "./m2"
      EXTRA_MAVEN_ARGS:
        required: false
        type: string
        default: ""
      USE_CI_POSTGRES:
        required: false
        type: boolean
        default: true
      RUN:
        required: false
        type: boolean
        default: true
      DATABASE:
        required: false
        type: string
        description: "Database to use: postgres or mysql"
        default: "postgres"
      CHECK_WORKDIR_CHANGES:
        required: true
        type: boolean
        default: false
      CHECK_CUSTOM_DIR:
        required: false
        type: string
        default: ""
      CHECK_CHANGES_BY_JOBS:
        required: false
        type: string
        default: "all"
      MAVEN_SERVER_USERNAME:
        required: false
        type: string
      MAVEN_SERVER_ID:
        required: false
        type: string
      RUN_ON:
        required: true
        type: string
      RUNNERS_CONTAINER_GROUP:
        required: true
        type: string


env:
  CHECK_DIR: ${{ inputs.WORKING_DIRECTORY }}

jobs:
  workdir-has-changes:
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container: buildpack-deps:24.04-scm
    outputs:
      changes-detected: ${{ steps.filter.outputs.changes-detected }}
    steps:
      - name: Set CHECK_DIR to custom directory if provided
        if: ${{ inputs.CHECK_CUSTOM_DIR != '' }}
        run: echo "CHECK_DIR=${{ inputs.CHECK_CUSTOM_DIR }}" >> $GITHUB_ENV
      - name: Set default CHECK_DIR
        if: ${{ inputs.CHECK_CUSTOM_DIR == '' }}
        run: echo "CHECK_DIR=${{ inputs.WORKING_DIRECTORY }}" >> $GITHUB_ENV

#      - name: Install Git
#        run: apt-get update && apt-get install -y git
      - name: Configure Git safe directory
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changes-detected:
              - "${{ env.CHECK_DIR }}/**"

  springboot-lint-check:
    needs: workdir-has-changes
    if: ${{ !inputs.CHECK_WORKDIR_CHANGES || (needs.workdir-has-changes.outputs.changes-detected == 'true' && (inputs.CHECK_CHANGES_BY_JOBS == 'all' || contains(fromJson(inputs.CHECK_CHANGES_BY_JOBS), github.job)))}}
    uses: ./.github/workflows/springboot-step-lint-check.yml
    with:
      JAVA_IMAGE: ${{inputs.JAVA_IMAGE}}
      WORKING_DIRECTORY: ${{inputs.WORKING_DIRECTORY}}
      MAVEN_USER_HOME: ${{inputs.MAVEN_USER_HOME}}
      EXTRA_MAVEN_ARGS: ${{inputs.EXTRA_MAVEN_ARGS}}
      RUN: ${{inputs.RUN}}
    secrets: inherit

  springboot-tests:
    needs: workdir-has-changes
    if: ${{ inputs.DATABASE == 'postgres' && (!inputs.CHECK_WORKDIR_CHANGES || (needs.workdir-has-changes.outputs.changes-detected == 'true' && (inputs.CHECK_CHANGES_BY_JOBS == 'all' || contains(fromJson(inputs.CHECK_CHANGES_BY_JOBS), github.job))))}}
    uses: ./.github/workflows/springboot-step-tests.yml
    with:
      JAVA_IMAGE: ${{inputs.JAVA_IMAGE}}
      WORKING_DIRECTORY: ${{inputs.WORKING_DIRECTORY}}
      MAVEN_USER_HOME: ${{inputs.MAVEN_USER_HOME}}
      EXTRA_MAVEN_ARGS: ${{inputs.EXTRA_MAVEN_ARGS}}
      MAVEN_SERVER_USERNAME: ${{ inputs.MAVEN_SERVER_USERNAME }}
      MAVEN_SERVER_ID: ${{ inputs.MAVEN_SERVER_ID }}
      COVERAGE_ARTIFACT_NAME: ${{ inputs.COVERAGE_ARTIFACT_NAME }}
      USE_CI_POSTGRES: ${{ inputs.USE_CI_POSTGRES }}
      RUN: ${{ inputs.RUN }}
    secrets: inherit

  springboot-tests-mysql:
    needs: workdir-has-changes
    if: ${{ inputs.DATABASE == 'mysql' && (!inputs.CHECK_WORKDIR_CHANGES || (needs.workdir-has-changes.outputs.changes-detected == 'true' && (inputs.CHECK_CHANGES_BY_JOBS == 'all' || contains(fromJson(inputs.CHECK_CHANGES_BY_JOBS), github.job))))}}
    uses: ./.github/workflows/springboot-step-tests-mysql.yml
    with:
      JAVA_IMAGE: ${{inputs.JAVA_IMAGE}}
      WORKING_DIRECTORY: ${{inputs.WORKING_DIRECTORY}}
      MAVEN_USER_HOME: ${{inputs.MAVEN_USER_HOME}}
      EXTRA_MAVEN_ARGS: ${{inputs.EXTRA_MAVEN_ARGS}}
      MAVEN_SERVER_USERNAME: ${{ inputs.MAVEN_SERVER_USERNAME }}
      MAVEN_SERVER_ID: ${{ inputs.MAVEN_SERVER_ID }}
      COVERAGE_ARTIFACT_NAME: ${{ inputs.COVERAGE_ARTIFACT_NAME }}
      RUN: ${{ inputs.RUN }}
    secrets: inherit

  jobs-succeded:
    needs: ["springboot-lint-check", "springboot-tests", "springboot-tests-mysql"]
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    if: ${{ always()}}
    steps:
      - name: "Jobs: springboot-lint-check, springboot-tests, springboot-tests-mysql didn't fail."
        run: if [[ "${{ needs.springboot-lint-check.result }}" == "failure" || "${{ needs.springboot-tests.result }}" == "failure" || "${{ needs.springboot-tests-mysql.result }}" == "failure" ]]; then exit 1; fi
