name: Run SpringBoot tests

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: 'zupit-agents'
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: 'Container'
      WORKING_DIRECTORY:
        required: true
        type: string
      JAVA_IMAGE:
        required: true
        type: string
      COVERAGE_ARTIFACT_NAME:
        required: true
        type: string
      MAVEN_USER_HOME:
        required: false
        type: string
        default: "./m2"
      EXTRA_MAVEN_ARGS:
        required: false
        type: string
        default: ""
      SPRING_APPLICATION_JSON:
        required: false
        type: string
      RUN:
        required: false
        type: boolean
        default: true
      MAVEN_SERVER_ID:
        required: false
        type: string
      MAVEN_SERVER_USERNAME:
        required: false
        type: string

env: "${{secrets}}"

jobs:
  springboot-run-tests:
    if: ${{ inputs.RUN }}
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container: ${{ inputs.JAVA_IMAGE }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set maven settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          path: "${{inputs.MAVEN_USER_HOME}}/settings.xml"
          servers: |
              [{ "id": "${{ inputs.MAVEN_SERVER_ID }},
                  "username": "${{ inputs.MAVEN_SERVER_USERNAME }}",
                  "password": "${{ secrets.CI_MAVEN_SERVER_PASSWORD }}"
              }]

      - name: Check settings and first password
        run: |

          echo "CI_MAVEN_SERVER_PASSWORD: $CI_MAVEN_SERVER_PASSWORD"



          cat ./m2/settings.xml


          echo MAVEN SETTINGS ${{ inputs.MAVEN_SETTINGS }}

          if [[ -n "${{ secrets.CI_MAVEN_SERVER_PASSWORD }}" ]]; then
            echo "CI_MAVEN_SERVER_PASSWORD secret exists"
          else
            echo "CI_MAVEN_SERVER_PASSWORD secret does not exist"
          fi

          # Extract only the first <password> value
          password=$(grep -oP '(?<=<password>).*?(?=</password>)' ./m2/settings.xml | head -n 1)

          length=${#password}
          last_char=${password: -1}

          echo "First Password Length: $length"
          echo "First Password Last Character: $last_char"


      - name: Run tests
        run: |
          ./mvnw -ntp verify --settings ${{inputs.MAVEN_USER_HOME}}/settings.xml -Dmaven.repo.local=${{inputs.MAVEN_USER_HOME}} ${{inputs.EXTRA_MAVEN_ARGS}}
          ./mvnw -ntp jacoco:report --settings ${{inputs.MAVEN_USER_HOME}}/settings.xml -Dmaven.repo.local=${{inputs.MAVEN_USER_HOME}} ${{inputs.EXTRA_MAVEN_ARGS}}
        env:
          SPRING_APPLICATION_JSON: ${{ inputs.SPRING_APPLICATION_JSON || '{}' }}
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test
          SPRING_DATASOURCE_USERNAME: test
          SPRING_DATASOURCE_PASSWORD: test

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.COVERAGE_ARTIFACT_NAME }}
          path: |
            ${{ inputs.WORKING_DIRECTORY }}/target/**/*.xml
            ${{ inputs.WORKING_DIRECTORY }}/target/**/*.class
          retention-days: 1

