name: Run SpringBoot tests

on:
  workflow_call:
    inputs:
      RUN_ON:
        required: false
        type: string
        default: 'zupit-agents'
      RUNNERS_CONTAINER_GROUP:
        required: false
        type: string
        default: 'Container'
      WORKING_DIRECTORY:
        required: true
        type: string
      JAVA_IMAGE:
        required: true
        type: string
      COVERAGE_ARTIFACT_NAME:
        required: true
        type: string
      MAVEN_USER_HOME:
        required: false
        type: string
        default: "./m2"
      EXTRA_MAVEN_ARGS:
        required: false
        type: string
        default: ""
      USE_CI_POSTGRES:
        required: false
        type: boolean
        default: true
      SPRING_APPLICATION_JSON:
        required: false
        type: string
      RUN:
        required: false
        type: boolean
        default: true
      MAVEN_SETTINGS:
        required: false
        type: string
        

env: "${{secrets}}"

jobs:
  springboot-run-tests:
    if: ${{ inputs.RUN }}
    runs-on:
      labels: ${{ inputs.RUN_ON }}
      group: ${{ inputs.RUNNERS_CONTAINER_GROUP }}
    container: ${{ inputs.JAVA_IMAGE }}

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: java-runner
          POSTGRES_PASSWORD: java-runner
          POSTGRES_DB: java

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set maven settings
        uses: s4u/maven-settings-action@v3.1.0
        with:
          servers: ${{ inputs.MAVEN_SETTINGS }}

      - name: Run tests
        run: |
          ./mvnw -ntp verify -Dmaven.repo.local=${{inputs.MAVEN_USER_HOME}} ${{inputs.EXTRA_MAVEN_ARGS}}
          ./mvnw -ntp jacoco:report -Dmaven.repo.local=${{inputs.MAVEN_USER_HOME}} ${{inputs.EXTRA_MAVEN_ARGS}}
        env:
          SPRING_APPLICATION_JSON: ${{ inputs.USE_CI_POSTGRES && inputs.SPRING_APPLICATION_JSON || '{}' }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.COVERAGE_ARTIFACT_NAME }}
          path: |
            ${{ inputs.WORKING_DIRECTORY }}/target/**/*.xml
            ${{ inputs.WORKING_DIRECTORY }}/target/**/*.class
          retention-days: 1
